// Report serializers: clean Markdown (for the CLI & docs) and JSON (for the API/UI).

import { truncate } from './util.js';

const STATUS_ICON = { pass: '✅', warn: '⚠️', fail: '❌', skip: '⏭️' };

export function reportToMarkdown(report) {
  const L = [];
  const m = report.meta;
  const o = report.overview;

  L.push(`# Search Visibility Analyzer — ${m.host}`);
  L.push('');
  L.push(`**Target:** ${m.targetUrl}`);
  if (m.finalUrl && m.finalUrl !== m.targetUrl) L.push(`**Final URL:** ${m.finalUrl}`);
  L.push(`**Analyzed:** ${new Date(m.analyzedAt).toUTCString()} · **HTTP ${m.httpStatus}** · took ${Math.round(m.durationMs / 1000)}s`);
  L.push('');
  L.push(`## Overall Visibility Index: **${o.visibilityIndex}/100** (${o.grade})`);
  L.push('');
  L.push(o.summary);
  L.push('');

  const order = [
    ['seo', 'SEO — Traditional Search (clicks)'],
    ['aeo', 'AEO — Answer Engines (direct answers)'],
    ['geo', 'GEO — Generative Engines (LLM citations)'],
  ];
  for (const [key, title] of order) {
    const cat = report.categories[key];
    L.push(`## ${title}`);
  L.push('');
    L.push(`**Score: ${cat.score}/100 — ${cat.grade}** · ${cat.passCount} pass, ${cat.warnCount} warn, ${cat.failCount} fail`);
    L.push('');
    L.push(`> ${cat.description}`);
    L.push('');
    for (const c of cat.checks) {
      if (c.status === 'skip') continue;
      const ev = c.evidence && typeof c.evidence === 'string' ? `\n> \`${truncate(c.evidence, 240).replace(/`/g, "'")}\`` : '';
      L.push(`- ${STATUS_ICON[c.status]} **${c.label}** — ${c.detail}${ev}`);
    }
    L.push('');
  }

  if (report.llm?.perspective) {
    const p = report.llm.perspective;
    L.push(`## GEO LLM Analysis`);
    L.push('');
    L.push(`> Simulated generative-engine read${report.llm.provider ? ` (model: ${report.llm.provider})` : ''}`);
    L.push('');
    L.push(`- **Entity identified:** ${p.entityIdentified} — ${p.entitySummary || 'n/a'}`);
    L.push(`- **Would cite:** ${p.wouldCite} (confidence ${p.confidence ?? 'n/a'}/100) — as: ${p.asWhat || 'n/a'}`);
    if (p.quoteFragment) L.push(`- **Most quotable line:** “${p.quoteFragment}”`);
    if (p.trustConcerns?.length) L.push(`- **Trust concerns:** ${p.trustConcerns.join('; ')}`);
    if (p.geoGaps?.length) L.push(`- **GEO gaps it flagged:** ${p.geoGaps.join('; ')}`);
    L.push('');
  } else if (report.llm?.skipped) {
    L.push(`## GEO LLM Analysis`);
    L.push('');
    L.push(`> ${report.llm.skipped}`);
    L.push('');
  }

  const page = report.page;
  L.push(`## Page Facts`);
  L.push('');
  L.push(`| Property | Value |`);
  L.push(`| --- | --- |`);
  L.push(`| Title | ${esc(page.title || '—')} |`);
  L.push(`| H1 | ${esc(page.h1 || '—')} |`);
  L.push(`| Words | ${page.wordCount} |`);
  L.push(`| Sentences | ${page.sentenceCount} |`);
  L.push(`| Flesch Reading Ease | ${page.flesch ?? '—'} |`);
  L.push(`| Flesch-Kincaid grade | ${page.fkgl ?? '—'} |`);
  L.push(`| Entity (inferred) | ${esc(page.brandGuess || '—')} |`);
  L.push(`| Schema types | ${esc((page.schemaTypes || []).slice(0, 8).join(', ') || 'none')} |`);
  L.push(`| Internal / external links | ${page.links.internal} / ${page.links.external} |`);
  L.push('');
  L.push('---');
  L.push('_Generated by the AI Search Visibility Analyzer (SEO·AEO·GEO). Lab-based Core Web Vitals; field data recommended for production decisions._');
  L.push('');
  return L.join('\n');
}

export function topActions(report) {
  // Highest-weight failing checks first, then warnings — the "fix this first" list.
  const actions = [];
  for (const [key, label] of [['seo', 'SEO'], ['aeo', 'AEO'], ['geo', 'GEO']]) {
    for (const c of report.categories[key].checks) {
      if (c.status === 'fail' || c.status === 'warn') {
        actions.push({ category: label, status: c.status, weight: c.weight, label: c.label, detail: c.detail });
      }
    }
  }
  actions.sort((a, b) => (a.status === b.status ? b.weight - a.weight : a.status === 'fail' ? -1 : 1));
  return actions.slice(0, 8).map((a) => `**[${a.category}]** ${a.label} — ${a.detail}`);
}

function esc(s) {
  return String(s).replace(/\|/g, '\\|').replace(/\n/g, ' ');
}
